### ISSUE TITLE
MoPA-RL: error: argument --gpu expected one argument

### ISSUE THREAD

**Issue by zichunxx** [clvrai/mopa-rl#2]
Hi, thank you for your generous sharing. I have installed all the libraries and when I execute code 
`sh ./scripts/2d/baseline.sh`, I encounter the following problem 
MoPA-RL: error: argument --gpu expected one argument.
Do u know how to fix it? Looking forward to your reply, thanks!

**Comment by djnhn** [comment]
hi,I encounter the same questions, do you slove the problems?
