### ISSUE TITLE
ompl no state space issue

### ISSUE THREAD

**Issue by tarunc20** [clvrai/mopa-rl#5]
Hi! I'm trying to set up the motion planner wrapper. I've cloned ompl (from the official source) into the mopa-rl directory, and run the setup commands. I then cd'ed into motion-planners and tried running the command, but ended up with this issue:
`cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
./src/mujoco_ompl_interface.cpp:2:10: fatal error: ompl/base/StateSpace.h: No such file or directory
    2 | #include <ompl/base/StateSpace.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1`
I'm not entirely sure where this is coming from, so if anyone had any insight, that would be greatly appreciated. Thanks!

**Comment by junjungoal** [comment]
@tarunc20 
Hi! 
Could you please check if ompl is correctly installed in `/usr/local/include`?
It needs to be `/usr/local/include/ompl`.

**Comment by tarunc20** [comment]
Thanks, this resolved the issue!
